### ISSUE TITLE
Failed to deserialize the Response: Foribidden (Only when runing the app from cli)

### ISSUE THREAD

**Issue by dcruz1990** [cloudinary/CloudinaryDotNet#223]
## Describe the bug in a sentence or two.
When try to upload a photo from the app (with dotnet run or dotnet watch run) i have Json Serialization Error: Foribbiden. However, when run from the VSCode debugger everything works fine.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[X ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Error screenshots or Stack Trace (if applicable)
 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: Failed to deserialize response with status code: Forbidden
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at CloudinaryDotNet.ApiShared.CreateResultFromString[T](String s, HttpStatusCode statusCode)
   --- End of inner exception stack trace ---

## OS and Version
OS: Arch Linux

## Versions and Libraries (fill in the version numbers)
Cloudinary .NET SDK version: 1.10.0
.NET Core - 3.0.1

**Comment by idobarnoam** [comment]
Hi @dcruz1990 
In our SDK we first try to parse the json response and retrieve the actual Cloudinary error that is received.
If you got the "forbidden" error it might mean that there is some configuration error with user and password.

Could you confirm that the environment variable or other user authentication configuration that you use is set up with the correct API key/secret?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at https://support.cloudinary.com/hc/en-us/requests/new or create a new ticket if you have any additional issues.
